# Site settings
title: "2050 podcast"
url: https://2050podcast.cz
email: podcast@2050podcast.cz
instagram: https://www.instagram.com/2050_podcast/
facebook: https://www.facebook.com/2050podcast
spotify: https://open.spotify.com/show/4vhMfZxkN7iUGQMVqEvOO8
apple-podcasts: https://podcasts.apple.com/us/podcast/2050/id1570604946
google-podcasts: https://www.google.com/podcasts?feed=aHR0cHM6Ly9hdWRpb2Jvb20uY29tL2NoYW5uZWxzLzUwNTA1NTIucnNz
youtube: https://www.youtube.com/channel/UCpW-nPyjH68BUfAjzhk7O_Q
rss: https://audioboom.com/channels/5050552.rss
github: faktaoklimatu/web-2050podcast
newsletter: "https://tinyletter.com/faktaoklimatu/subscribe"
fundraising: "https://www.darujme.cz/projekt/1203742"
author: Fakta o klimatu
copyright: "&copy; 2021 Otevřená data o klimatu, z. ú."
description: Klimatický podcast o budoucnosti, ve které nám nepoteče do bot.
keywords: klima, změna klimatu, podcast

# Set permalinks in local language
collections:
  pages:
    output: true
    permalink: /:title
    title: stránky
    weight: 0
  episodes:
    output: true
    permalink: /epizody/:title
    title: epizody
    weight: 1

# CDN links and hashes
cdn:
    # See https://www.srihash.org for info on how to generate the hashes or find the library on https://cdnjs.com/
    bootstrap_css:      "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
    bootstrap_css_hash: "sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
    fa:                 "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    fa_hash:            "sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
    jquery:             "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    jquery_hash:        "sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    bootstrap_js:       "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"
    bootstrap_js_hash:  "sha512-wV7Yj1alIZDqZFCUQJy85VN+qvEIly93fIQAN7iqDFCPEucLCeNFz4r35FCo9s6WrpdDQPi80xbljXB8Bjtvcg=="

# What files to include/exclude from final site?
include: [ ".well-known" ] # .well-known-templates implicitly excluded
exclude:
    - README.md            # Developer information
    - LICENSE.md           # Developer information
    - CONTRIBUTORS.md      # Developer information
    - Gemfile              # Build settings
    - Gemfile.lock         # Build settings
    - Makefile             # Build settings
    - firebase.json        # Deploy settings
    - utils                # Development files
    - Dockerfile           # Containerization
    - .cache/               # Intermediate files

sass:
    sass_dir: assets/_scss
    style: compressed
cache_dir: .cache
force_polling: true    # Force polling to resolve Windows issues with watch

# Set folders for global and local plugins
plugins_dir: [ _plugins ]

# Enable external plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-last-modified-at

target-blank:
    add_css_classes: ext-link

# Enable Czech smart quotes
kramdown:
  smart_quotes: sbquo,lsquo,bdquo,ldquo
